[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  SECRETS_SCAN_OMIT_KEYS = "VITE_SUPABASE_URL,VITE_SUPABASE_ANON_KEY,VITE_RESEND_API_KEY"
  SECRETS_SCAN_OMIT_PATHS = "tests/**/*,testing/**/*,test-results/**/*,playwright-report/**/*,docs/**/*,.taskmaster/**/*,memory-bank/**/*,scripts/**/*"
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.paypal.com https://www.sandbox.paypal.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://vlvamfplfqgmosokuxqm.supabase.co https://api-m.sandbox.paypal.com https://www.paypal.com; frame-src https://www.paypal.com https://www.sandbox.paypal.com;"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# SPA redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Deploy previews configuration
[context.deploy-preview]
  command = "npm run build"

[context.branch-deploy]
  command = "npm run build"

# Production context
[context.production]
  command = "npm run build"

# Edge Functions Configuration
# Admin Functions
[[edge_functions]]
  path = "/api/admin-get-users"
  function = "admin-get-users"

[[edge_functions]]
  path = "/api/admin-get-user-activity"
  function = "admin-get-user-activity"

[[edge_functions]]
  path = "/api/admin-get-user-subscriptions"
  function = "admin-get-user-subscriptions"

[[edge_functions]]
  path = "/api/admin-update-user-status"
  function = "admin-update-user-status"

[[edge_functions]]
  path = "/api/admin-update-user-role"
  function = "admin-update-user-role"

# PayPal Functions
[[edge_functions]]
  path = "/api/create-paypal-subscription"
  function = "create-paypal-subscription"

[[edge_functions]]
  path = "/api/get-paypal-subscription-details"
  function = "get-paypal-subscription-details"

[[edge_functions]]
  path = "/api/get-paypal-plan-details"
  function = "get-paypal-plan-details"

[[edge_functions]]
  path = "/api/create-paypal-product-plan"
  function = "create-paypal-product-plan"

[[edge_functions]]
  path = "/api/cancel-paypal-subscription"
  function = "cancel-paypal-subscription"

# Webhook Handler
[[edge_functions]]
  path = "/api/webhook-handler"
  function = "webhook-handler"
