
[functions.create-paypal-product-plan]
enabled = true
verify_jwt = true
import_map = "./functions/create-paypal-product-plan/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create-paypal-product-plan/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create-paypal-product-plan/*.html" ]

[functions.create-paypal-subscription]
enabled = true
verify_jwt = true
import_map = "./functions/create-paypal-subscription/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create-paypal-subscription/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create-paypal-subscription/*.html" ]

[functions.get-paypal-subscription-details]
enabled = true
verify_jwt = true
import_map = "./functions/get-paypal-subscription-details/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/get-paypal-subscription-details/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/get-paypal-subscription-details/*.html" ]

[functions.webhook-handler]
enabled = true
verify_jwt = true
import_map = "./functions/webhook-handler/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/webhook-handler/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/webhook-handler/*.html" ]

[functions.admin-get-user-subscriptions]
enabled = true
verify_jwt = true
import_map = "./functions/admin-get-user-subscriptions/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/admin-get-user-subscriptions/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/admin-get-user-subscriptions/*.html" ]
